
export const COMMON = {
  SERVER_REQUEST: 'SERVER_REQUEST',
  SERVER_SUCCESS: 'SERVER_SUCCESS',
}

export const USER = {
	LOGIN: 'LOGIN',
	SIGNUP: 'SIGNUP',
	USER_SETTING: 'USER_SETTING',
  	OUT: 'OUT',
  	CHECK_EMAIL: 'CHECK_EMAIL',
}

export const MAIN = {
	BRANDS: 'BRANDS',
	CELEBRITIES: 'CELEBRITIES',
}